#!/usr/bin/env node

// X-CLI
// @Author: YiJun(sihao)
// @VERISON 0.0.1
const INFO = require('./package.json');

const cli = require('commander');
const colors = require('colors');
const commands = ['init', 'dev', 'lint', 'build', 'preview', 'upgrade', 'publish'];

const cmd_init = require('./scripts/init');
const cmd_dev = require('./scripts/dev');
const cmd_build = require('./scripts/build');
const cmd_preview = require('./scripts/preview');
const cmd_upgrade = require('./scripts/upgrade');
const cmd_publish = require('./scripts/publish');
// const cmd_lint = require('./scripts/lint');

cli
  .version(INFO.version)
  .usage('[command]'.green)
  .description(INFO.description.red);

// Register Command
cli
  .command('init [ProjectName]')
  .description('init Project'.red)
  .action(cmd_init);

cli
  .command('dev')
  .description('start development server'.red)
  .action(cmd_dev);

cli
  .command('build')
  .description('building'.red)
  .action(cmd_build);

cli
  .command('preview')
  .description('building and preview'.red)
  .action(cmd_preview);

cli
  .command('upgrade')
  .description('upgrade xcli'.red)
  .action(cmd_upgrade);

cli
  .command('publish')
  .description('publish current project'.red)
  .action(cmd_publish);

// cli
//   .command('lint <path> [param]')
//   .description('lint code style'.red)
//   .action(cmd_lint);

cli
  .command('help')
  .description('check help infomation'.green)
  .action(() => cli.help());

cli.parse(process.argv);

if (!cli.args.length || !process.argv[2] || !commands.includes(process.argv[2]))
  cli.help();
